rm: cannot remove '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/result/*': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop27
Removing network hadoop27_default
Network hadoop27_default not found.
Creating network "hadoop27_default" with the default driver
Pulling scm (apache/ozone-runner:20190717-1)...
20190717-1: Pulling from apache/ozone-runner
Digest: sha256:00bb9519e6d236c50761dcc9c668ce7f04a74f160b916bf3baeaa26232389a69
Status: Downloaded newer image for apache/ozone-runner:20190717-1
Pulling nm (flokkr/hadoop:2.7.7)...
2.7.7: Pulling from flokkr/hadoop
Digest: sha256:594a1cc971f4e91218132f2027617859d4624a55bda01bc43ec07545022ac6c9
Status: Downloaded newer image for flokkr/hadoop:2.7.7
Creating hadoop27_om_1 ... 
Creating hadoop27_nm_1 ... 
Creating hadoop27_s3g_1 ... 
Creating hadoop27_rm_1  ... 
Creating hadoop27_scm_1 ... 
Creating hadoop27_datanode_1 ... 
Creating hadoop27_datanode_2 ... 
Creating hadoop27_datanode_3 ... 
Creating hadoop27_nm_1       ... done
Creating hadoop27_om_1       ... done
Creating hadoop27_rm_1       ... done
Creating hadoop27_s3g_1      ... done
Creating hadoop27_datanode_3 ... done
Creating hadoop27_datanode_2 ... done
Creating hadoop27_datanode_1 ... done
Creating hadoop27_scm_1      ... done
3 datanodes are up and registered to the scm
==============================================================================
hadoop27-createmrenv :: Create directories required for MR test               
==============================================================================
Create test volume, bucket and key                                    | PASS |
------------------------------------------------------------------------------
Create user dir for hadoop                                            | PASS |
------------------------------------------------------------------------------
hadoop27-createmrenv :: Create directories required for MR test       | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /tmp/smoketest/hadoop27/result/robot-hadoop27-hadoop27-createmrenv-scm.xml
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/7) Installing libbz2 (1.0.6-r7)
(2/7) Installing libffi (3.2.1-r4)
(3/7) Installing gdbm (1.13-r1)
(4/7) Installing sqlite-libs (3.25.3-r2)
(5/7) Installing python2 (2.7.15-r2)
(6/7) Installing py-setuptools (39.1.0-r0)
(7/7) Installing py2-pip (10.0.1-r0)
Executing busybox-1.28.4-r0.trigger
Executing glibc-bin-2.27-r0.trigger
OK: 93 MiB in 45 packages
Collecting robotframework
  Downloading https://files.pythonhosted.org/packages/22/0f/1b9ffa0c4e59789b50e6034866e823b7d4a5c7eaedad7bfd0bba42f2aa9d/robotframework-3.1.2-py2.py3-none-any.whl (602kB)
Installing collected packages: robotframework
Successfully installed robotframework-3.1.2
You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
==============================================================================
hadoop27-hadoopo3fs :: Test ozone fs with hadoopfs                            
==============================================================================
Test hadoop dfs                                                       | PASS |
------------------------------------------------------------------------------
hadoop27-hadoopo3fs :: Test ozone fs with hadoopfs                    | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /tmp/smoketest/hadoop27/result/robot-hadoop27-hadoop27-hadoopo3fs-rm.xml
==============================================================================
hadoop27-mapreduce :: Execute MR jobs                                         
==============================================================================
Execute PI calculation                                                | PASS |
------------------------------------------------------------------------------
Execute WordCount                                                     | FAIL |
1 != 0
------------------------------------------------------------------------------
hadoop27-mapreduce :: Execute MR jobs                                 | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /tmp/smoketest/hadoop27/result/robot-hadoop27-hadoop27-mapreduce-rm.xml
Connection pool is full, discarding connection: 0.0.0.0
Stopping hadoop27_datanode_1 ... 
Stopping hadoop27_scm_1      ... 
Stopping hadoop27_datanode_2 ... 
Stopping hadoop27_datanode_3 ... 
Stopping hadoop27_om_1       ... 
Stopping hadoop27_s3g_1      ... 
Stopping hadoop27_rm_1       ... 
Stopping hadoop27_nm_1       ... 
Stopping hadoop27_nm_1       ... done
Stopping hadoop27_rm_1       ... done
Stopping hadoop27_om_1       ... done
Stopping hadoop27_scm_1      ... done
Stopping hadoop27_s3g_1      ... done
Stopping hadoop27_datanode_1 ... done
Stopping hadoop27_datanode_2 ... done
Stopping hadoop27_datanode_3 ... done
Removing hadoop27_datanode_1 ... 
Removing hadoop27_scm_1      ... 
Removing hadoop27_datanode_2 ... 
Removing hadoop27_datanode_3 ... 
Removing hadoop27_om_1       ... 
Removing hadoop27_s3g_1      ... 
Removing hadoop27_rm_1       ... 
Removing hadoop27_nm_1       ... 
Removing hadoop27_datanode_1 ... done
Removing hadoop27_rm_1       ... done
Removing hadoop27_scm_1      ... done
Removing hadoop27_datanode_3 ... done
Removing hadoop27_om_1       ... done
Removing hadoop27_s3g_1      ... done
Removing hadoop27_nm_1       ... done
Removing hadoop27_datanode_2 ... done
Removing network hadoop27_default
Log:     /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop27/result/log.html
Report:  /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop27/result/report.html
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop27 is FAILED!!!!
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop31
Removing network hadoop31_default
Network hadoop31_default not found.
Creating network "hadoop31_default" with the default driver
Pulling nm (flokkr/hadoop:3.1.2)...
3.1.2: Pulling from flokkr/hadoop
Digest: sha256:aaed24f2f15ef520340c98c99c96c62056e018fdfe4591b8dfdfa8fd50636dc1
Status: Downloaded newer image for flokkr/hadoop:3.1.2
Creating hadoop31_om_1 ... 
Creating hadoop31_nm_1 ... 
Creating hadoop31_rm_1 ... 
Creating hadoop31_s3g_1 ... 
Creating hadoop31_scm_1 ... 
Creating hadoop31_datanode_1 ... 
Creating hadoop31_datanode_2 ... 
Creating hadoop31_datanode_3 ... 
Creating hadoop31_om_1       ... done
Creating hadoop31_rm_1       ... done
Creating hadoop31_scm_1      ... done
Creating hadoop31_s3g_1      ... done
Creating hadoop31_datanode_3 ... done
Creating hadoop31_datanode_1 ... done
Creating hadoop31_nm_1       ... done
Creating hadoop31_datanode_2 ... done
0 datanode is up and healthy (until now)
3 datanodes are up and registered to the scm
==============================================================================
hadoop31-createmrenv :: Create directories required for MR test               
==============================================================================
Create test volume, bucket and key                                    | PASS |
------------------------------------------------------------------------------
Create user dir for hadoop                                            | PASS |
------------------------------------------------------------------------------
hadoop31-createmrenv :: Create directories required for MR test       | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /tmp/smoketest/hadoop31/result/robot-hadoop31-hadoop31-createmrenv-scm.xml
fork/exec /usr/local/bin/docker-containerd-shim: cannot allocate memory
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop31 is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop31/result/docker-*.log': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop32
sh: fork: Cannot allocate memory
Removing network hadoop32_default
Network hadoop32_default not found.
Creating network "hadoop32_default" with the default driver
Pulling nm (apache/hadoop:3)...
3: Pulling from apache/hadoop
failed to register layer: ApplyLayer exit status 2 stdout:  stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x164aade m=0 sigcode=18446744073709551610

goroutine 0 [idle]:

goroutine 1 [runnable, locked to thread]:
runtime.gcenable()
	/usr/local/go/src/runtime/mgc.go:210 +0x9a
runtime.main()
	/usr/local/go/src/runtime/proc.go:151 +0x12a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x27f1d58
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x2
rsi    0x7ffc9e85b970
rbp    0x1cc3200
rsp    0x7ffc9e85b9e8
r8     0x0
r9     0x6
r10    0x8
r11    0x246
r12    0x3539c20
r13    0x34
r14    0x0
r15    0xf3
rip    0x164aade
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

Removing network hadoop32_default
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop32 is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-mr/hadoop32/result/robot-*.xml': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-recon
Removing network ozone-recon_default
Network ozone-recon_default not found.
Creating network "ozone-recon_default" with the default driver
Creating ozone-recon_scm_1 ... 
Creating ozone-recon_om_1  ... 
Creating ozone-recon_recon_1 ... 
Creating ozone-recon_datanode_1 ... 
Creating ozone-recon_datanode_2 ... 
Creating ozone-recon_datanode_3 ... 
Creating ozone-recon_om_1       ... error

ERROR: for ozone-recon_om_1  Cannot start service om: driver failed programming external connectivity on endpoint ozone-recon_om_1 (a5208757dc121584619e6201030f31f100dfab80f3147ad902b435dfca27b877): Bind for 0.0.0.0:9874 failed: port is already allocated
Creating ozone-recon_datanode_1 ... error
Creating ozone-recon_scm_1      ... error

ERROR: for ozone-recon_scm_1  Cannot start service scm: driver failed programming external connectivity on endpoint ozone-recon_scm_1 (167936615b9e223a385ab35c1fca90afd0f0f315f7f2f1232db65923c863d13a): Bind for 0.0.0.0:9876 failed: port is already allocated
Creating ozone-recon_datanode_2 ... error
Creating ozone-recon_recon_1    ... error

ERROR: for ozone-recon_recon_1  Cannot start service recon: shim error: fork/exec /usr/local/bin/docker-runc: cannot allocate memory
Creating ozone-recon_datanode_3 ... error

ERROR: for ozone-recon_datanode_1  Cannot start service datanode: driver failed programming external connectivity on endpoint ozone-recon_datanode_1 (6de0b6ed956d0183a2b670fe2e60a9bec0282276203d752c28ab4987f085b0b5):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32786 -j DNAT --to-destination 172.19.0.4:9864 ! -i br-db3baac93d65:  (fork/exec /sbin/iptables: cannot allocate memory))

ERROR: for ozone-recon_datanode_3  Cannot start service datanode: shim error: fork/exec /usr/local/bin/docker-runc: cannot allocate memory

ERROR: for ozone-recon_datanode_2  Cannot start service datanode: oci runtime error: container_linux.go:295: starting container process caused "process_linux.go:274: starting init process command caused \"fork/exec /proc/self/exe: cannot allocate memory\""


ERROR: for scm  Cannot start service scm: driver failed programming external connectivity on endpoint ozone-recon_scm_1 (167936615b9e223a385ab35c1fca90afd0f0f315f7f2f1232db65923c863d13a): Bind for 0.0.0.0:9876 failed: port is already allocated

ERROR: for recon  Cannot start service recon: shim error: fork/exec /usr/local/bin/docker-runc: cannot allocate memory

ERROR: for om  Cannot start service om: driver failed programming external connectivity on endpoint ozone-recon_om_1 (a5208757dc121584619e6201030f31f100dfab80f3147ad902b435dfca27b877): Bind for 0.0.0.0:9874 failed: port is already allocated

ERROR: for datanode  Cannot start service datanode: driver failed programming external connectivity on endpoint ozone-recon_datanode_1 (6de0b6ed956d0183a2b670fe2e60a9bec0282276203d752c28ab4987f085b0b5):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32786 -j DNAT --to-destination 172.19.0.4:9864 ! -i br-db3baac93d65:  (fork/exec /sbin/iptables: cannot allocate memory))
Encountered errors while bringing up the project.
Removing ozone-recon_recon_1    ... 
Removing ozone-recon_datanode_3 ... 
Removing ozone-recon_scm_1      ... 
Removing ozone-recon_datanode_1 ... 
Removing ozone-recon_datanode_2 ... 
Removing ozone-recon_om_1       ... 
Removing ozone-recon_om_1       ... done
Removing ozone-recon_recon_1    ... done
Removing ozone-recon_datanode_1 ... done
Removing ozone-recon_datanode_3 ... done
Removing ozone-recon_datanode_2 ... done
Removing ozone-recon_scm_1      ... done
Removing network ozone-recon_default
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-recon is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-recon/result/robot-*.xml': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-topology
Removing network ozone-topology_net
Network ozone-topology_net not found.
Creating network "ozone-topology_net" with driver "bridge"
Creating ozone-topology_datanode_1_1 ... 
Creating ozone-topology_datanode_3_1 ... 
Creating ozone-topology_om_1         ... 
Creating ozone-topology_scm_1        ... 
Creating ozone-topology_datanode_4_1 ... 
Creating ozone-topology_datanode_2_1 ... 
Creating ozone-topology_datanode_1_1 ... error

ERROR: for ozone-topology_datanode_1_1  Cannot start service datanode_1: driver failed programming external connectivity on endpoint ozone-topology_datanode_1_1 (8902db8e45ceac839a151e6a66b127ae21c3a2de7f26feba8cb949c9bd76af27):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32808 -j DNAT --to-destination 10.5.0.4:9864 ! -i br-0dbadcc95698:  (fork/exec /sbin/iptables: cannot allocate memory))
Creating ozone-topology_om_1         ... error

ERROR: for ozone-topology_om_1  Cannot start service om: driver failed programming external connectivity on endpoint ozone-topology_om_1 (81f298f3f91b9fbbbce21a18d89e48a2636c6a8577d156f46679d98e2032c64d): Bind for 0.0.0.0:9874 failed: port is already allocated
Creating ozone-topology_scm_1        ... error

ERROR: for ozone-topology_scm_1  Cannot start service scm: driver failed programming external connectivity on endpoint ozone-topology_scm_1 (c0d30189147a5298e64cbc62fe00dea4390498c4541d12714a5deb9155d16584): Bind for 0.0.0.0:9876 failed: port is already allocated
Creating ozone-topology_datanode_4_1 ... error

ERROR: for ozone-topology_datanode_4_1  Cannot start service datanode_4: oci runtime error: container_linux.go:295: starting container process caused "process_linux.go:274: starting init process command caused \"fork/exec /proc/self/exe: cannot allocate memory\""

Creating ozone-topology_datanode_2_1 ... error

ERROR: for ozone-topology_datanode_2_1  Cannot start service datanode_2: fork/exec /usr/local/bin/docker-containerd-shim: cannot allocate memory
Creating ozone-topology_datanode_3_1 ... error

ERROR: for ozone-topology_datanode_3_1  Cannot start service datanode_3: containerd: container not started

ERROR: for scm  Cannot start service scm: driver failed programming external connectivity on endpoint ozone-topology_scm_1 (c0d30189147a5298e64cbc62fe00dea4390498c4541d12714a5deb9155d16584): Bind for 0.0.0.0:9876 failed: port is already allocated

ERROR: for om  Cannot start service om: driver failed programming external connectivity on endpoint ozone-topology_om_1 (81f298f3f91b9fbbbce21a18d89e48a2636c6a8577d156f46679d98e2032c64d): Bind for 0.0.0.0:9874 failed: port is already allocated

ERROR: for datanode_3  Cannot start service datanode_3: containerd: container not started

ERROR: for datanode_2  Cannot start service datanode_2: fork/exec /usr/local/bin/docker-containerd-shim: cannot allocate memory

ERROR: for datanode_1  Cannot start service datanode_1: driver failed programming external connectivity on endpoint ozone-topology_datanode_1_1 (8902db8e45ceac839a151e6a66b127ae21c3a2de7f26feba8cb949c9bd76af27):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32808 -j DNAT --to-destination 10.5.0.4:9864 ! -i br-0dbadcc95698:  (fork/exec /sbin/iptables: cannot allocate memory))

ERROR: for datanode_4  Cannot start service datanode_4: oci runtime error: container_linux.go:295: starting container process caused "process_linux.go:274: starting init process command caused \"fork/exec /proc/self/exe: cannot allocate memory\""

Encountered errors while bringing up the project.
Connection pool is full, discarding connection: 0.0.0.0
Removing ozone-topology_datanode_2_1 ... 
Removing ozone-topology_datanode_4_1 ... 
Removing ozone-topology_scm_1        ... 
Removing ozone-topology_datanode_3_1 ... 
Removing ozone-topology_om_1         ... 
Removing ozone-topology_datanode_1_1 ... 
Removing ozone-topology_scm_1        ... done
Removing ozone-topology_om_1         ... done
Removing ozone-topology_datanode_1_1 ... done
Removing ozone-topology_datanode_4_1 ... done
Removing ozone-topology_datanode_2_1 ... done
Removing ozone-topology_datanode_3_1 ... done
Removing network ozone-topology_net
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-topology is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone-topology/result/robot-*.xml': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone
Removing network ozone_default
Network ozone_default not found.
Creating network "ozone_default" with the default driver
Creating ozone_scm_1 ... 
Creating ozone_om_1  ... 
Creating ozone_datanode_1 ... 
Creating ozone_datanode_2 ... 
Creating ozone_datanode_3 ... 
Creating ozone_om_1       ... error

ERROR: for ozone_om_1  Cannot start service om: driver failed programming external connectivity on endpoint ozone_om_1 (6f96c802d975fcd23351feb2bd10b80bd57f709890c8ddc9419bec46b4473be7): Bind for 0.0.0.0:9874 failed: port is already allocated
Creating ozone_scm_1      ... error

ERROR: for ozone_scm_1  Cannot start service scm: driver failed programming external connectivity on endpoint ozone_scm_1 (6b16cd8b0963edcf4db7b9da404a831b869fd01b7c9f82ba4907d09226225dd2): Bind for 0.0.0.0:9876 failed: port is already allocated
Creating ozone_datanode_2 ... error
Creating ozone_datanode_3 ... error
Creating ozone_datanode_1 ... error

ERROR: for ozone_datanode_1  Cannot start service datanode: open /var/run/docker/libcontainerd/containerd/646a6bc79db5192c72395e068de909fe841d928dc9d878808de3297ee42dade8/init/shim-log.json: no such file or directory

ERROR: for ozone_datanode_3  Cannot start service datanode: fork/exec /usr/local/bin/docker-containerd-shim: cannot allocate memory

ERROR: for ozone_datanode_2  Cannot start service datanode: driver failed programming external connectivity on endpoint ozone_datanode_2 (560c54e4630634a0d1197980e7bc1648dd6017b1fa05d48fc3d54608c5964941):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32826 -j DNAT --to-destination 172.19.0.3:9882 ! -i br-81bcff56245f:  (fork/exec /sbin/iptables: cannot allocate memory))

ERROR: for scm  Cannot start service scm: driver failed programming external connectivity on endpoint ozone_scm_1 (6b16cd8b0963edcf4db7b9da404a831b869fd01b7c9f82ba4907d09226225dd2): Bind for 0.0.0.0:9876 failed: port is already allocated

ERROR: for om  Cannot start service om: driver failed programming external connectivity on endpoint ozone_om_1 (6f96c802d975fcd23351feb2bd10b80bd57f709890c8ddc9419bec46b4473be7): Bind for 0.0.0.0:9874 failed: port is already allocated

ERROR: for datanode  Cannot start service datanode: open /var/run/docker/libcontainerd/containerd/646a6bc79db5192c72395e068de909fe841d928dc9d878808de3297ee42dade8/init/shim-log.json: no such file or directory
Encountered errors while bringing up the project.
Removing ozone_datanode_1 ... 
Removing ozone_datanode_2 ... 
Removing ozone_scm_1      ... 
Removing ozone_datanode_3 ... 
Removing ozone_om_1       ... 
Removing ozone_om_1       ... done
Removing ozone_datanode_1 ... done
Removing ozone_datanode_3 ... done
Removing ozone_scm_1      ... done
Removing ozone_datanode_2 ... done
Removing network ozone_default
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozone/result/robot-*.xml': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozoneperf
Removing network ozoneperf_default
Network ozoneperf_default not found.
Creating network "ozoneperf_default" with the default driver
Pulling jaeger (jaegertracing/all-in-one:latest)...
latest: Pulling from jaegertracing/all-in-one
Digest: sha256:b0a0c3458e748839022af9d3e98a1831fbc0984f800f88bae3071a84efa21015
Status: Downloaded newer image for jaegertracing/all-in-one:latest
Pulling grafana (grafana/grafana:)...
latest: Pulling from grafana/grafana
Digest: sha256:a10521576058f40427306fcb5be48138c77ea7c55ede24327381211e653f478a
Status: Downloaded newer image for grafana/grafana:latest
Pulling prometheus (prom/prometheus:)...
latest: Pulling from prom/prometheus
failed to register layer: ApplyLayer exit status 2 stdout:  stderr: runtime/cgo: runtime/cgo: pthread_create failed: Resource temporarily unavailable
pthread_create failed: Resource temporarily unavailable

SIGABRT: abort
PC=0x164aade m=3 sigcode=18446744073709551610

goroutine 0 [idle]:

goroutine 1 [running, locked to thread]:
	goroutine running on other thread; stack unavailable

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 18 [syscall]:
os/signal.signal_recv(0x7286fb)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

rax    0x0
rbx    0x27f1d58
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x2
rsi    0x7f244e57e720
rbp    0x1cc3200
rsp    0x7f244e57e798
r8     0x0
r9     0x6
r10    0x8
r11    0x246
r12    0x7f24480008c0
r13    0x34
r14    0x0
r15    0xf3
rip    0x164aade
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

Removing network ozoneperf_default
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozoneperf is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozoneperf/result/robot-*.xml': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozones3-haproxy
./test.sh: fork: Cannot allocate memory
./test.sh: line 22: /../testlib.sh: No such file or directory
./test.sh: line 24: start_docker_env: command not found
./test.sh: line 26: execute_robot_test: command not found
./test.sh: line 28: stop_docker_env: command not found
./test.sh: line 30: generate_report: command not found
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozones3-haproxy is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozones3-haproxy/result/robot-*.xml': No such file or directory
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozones3-haproxy/result/docker-*.log': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozones3
./test.sh: fork: Cannot allocate memory
./test.sh: line 22: /../testlib.sh: No such file or directory
./test.sh: line 24: start_docker_env: command not found
./test.sh: line 26: execute_robot_test: command not found
./test.sh: line 28: execute_robot_test: command not found
./test.sh: line 30: stop_docker_env: command not found
./test.sh: line 32: generate_report: command not found
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozones3 is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozones3/result/robot-*.xml': No such file or directory
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozones3/result/docker-*.log': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozonesecure-mr
./test.sh: fork: Cannot allocate memory
./test.sh: line 22: /../testlib.sh: No such file or directory
./test.sh: line 26: start_docker_env: command not found
./test.sh: line 28: execute_robot_test: command not found
./test.sh: line 30: execute_robot_test: command not found
./test.sh: line 36: /../testlib.sh: No such file or directory
./test.sh: line 38: execute_robot_test: command not found
./test.sh: line 40: execute_robot_test: command not found
./test.sh: line 42: stop_docker_env: command not found
./test.sh: line 44: generate_report: command not found
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozonesecure-mr is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozonesecure-mr/result/robot-*.xml': No such file or directory
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozonesecure-mr/result/docker-*.log': No such file or directory
Executing test in /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozonesecure
./test.sh: fork: Cannot allocate memory
./test.sh: line 22: /../testlib.sh: No such file or directory
./test.sh: line 26: start_docker_env: command not found
./test.sh: line 28: execute_robot_test: command not found
./test.sh: line 30: execute_robot_test: command not found
./test.sh: line 32: execute_robot_test: command not found
./test.sh: line 34: execute_robot_test: command not found
./test.sh: line 36: execute_robot_test: command not found
./test.sh: line 38: execute_robot_test: command not found
./test.sh: line 40: stop_docker_env: command not found
./test.sh: line 42: generate_report: command not found
ERROR: Test execution of /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozonesecure is FAILED!!!!
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozonesecure/result/robot-*.xml': No such file or directory
cp: cannot stat '/workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/ozonesecure/result/docker-*.log': No such file or directory
Log:     /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/result/log.html
Report:  /workdir/hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/compose/result/report.html
